[[redirects]]
  from = "/apple-app-site-association"
  to = "/apple-app-site-association.json"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/apple-app-site-association"

  [headers.values]
    Content-Type = "application/pkcs7-mime"

